openapi: 3.0.0
info:
  title: Backend Challenges
  version: 1.0.0
servers:
  - url: http://{{host_url}}
paths:
  /analysis:
    post:
      tags:
        - default
      summary: Create a Workflow
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                clientId: client123
                geoJson:
                  type: Polygon
                  coordinates:
                    - - - -63.624885020050996
                        - -10.311050368263523
                      - - -63.624885020050996
                        - -10.367865108370523
                      - - -63.61278302732815
                        - -10.367865108370523
                      - - -63.61278302732815
                        - -10.311050368263523
                      - - -63.624885020050996
                        - -10.311050368263523
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  workflowId:
                    type: string
                    format: uuid
                  message:
                    type: string
              example:
                workflowId: "6c902cd5-cd20-4ea3-90cc-299e2b5f24a2"
                message: "Workflow created and tasks queued from YAML definition."
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Invalid request body"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Failed to create workflow"
  
  /workflows/{workflowId}/status:
    get:
      tags:
        - default
      summary: Get Workflow Status by ID
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: workflowId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  workflowId:
                    type: string
                  status:
                    type: string
                  completedTasks:
                    type: integer
                  totalTasks:
                    type: integer
              example:
                workflowId: "ad3f4001-227e-4166-9bfb-580fe95317da"
                status: "completed"
                completedTasks: 4
                totalTasks: 4
        '404':
          description: Workflow not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Workflow not found, workflowId: ad3f4001-227e-4166-9bfb-580fe95317da"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Failed to fetch workflow status"

  /workflows/{workflowId}/results:
    get:
      tags:
        - default
      summary: Get Workflow Results by ID
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: workflowId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  workflowId:
                    type: string
                  status:
                    type: string
                  finalResult:
                    type: array
                    items:
                      type: object
                      properties:
                        taskId:
                          type: string
                        type:
                          type: string
                        output:
                          type: object
                        status:
                          type: string
              example:
                workflowId: "6c902cd5-cd20-4ea3-90cc-299e2b5f24a2"
                status: "completed"
                finalResult:
                  - taskId: "edd59e8b-68d9-4518-8a51-1a23fd58e04a"
                    type: "analysis"
                    output: null
                    status: "completed"
                  - taskId: "d5e0065d-0794-4818-9e8b-7e747306f7f8"
                    type: "polygon_area"
                    output: "{\"area\":8363324.273315565}"
                    status: "completed"
                  - taskId: "7fd54d68-20b4-4852-8427-55956099ce43"
                    type: "notification"
                    output: null
                    status: "completed"
                  - taskId: "45a7ca20-f61a-43b0-84c1-f591e3c638cc"
                    type: "report_generation"
                    output:
                      workflowId: "6c902cd5-cd20-4ea3-90cc-299e2b5f24a2"
                      tasks:
                        - taskId: "edd59e8b-68d9-4518-8a51-1a23fd58e04a"
                          type: "analysis"
                          output: null
                          error: null
                        - taskId: "d5e0065d-0794-4818-9e8b-7e747306f7f8"
                          type: "polygon_area"
                          output: "{\"area\":8363324.273315565}"
                          error: null
                        - taskId: "7fd54d68-20b4-4852-8427-55956099ce43"
                          type: "notification"
                          output: null
                          error: null
                      finalReport: "Aggregated data and results"
                    status: "completed"
        '404':
          description: Workflow not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Workflow not found, workflowId: 6c902cd5-cd20-4ea3-90cc-299e2b5f24a2"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Workflow is not yet completed"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Failed to fetch workflow results"

